name: Node.js CI

on: [push]

env:
  DATABASE_TYPE: postgresql
  SKIP_DB_CHECK: 1

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
        - node-version: 22.13
          db-type: postgresql
        - node-version: 22.13
          db-type: mysql

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
      env:
        DATABASE_TYPE: ${{ matrix.db-type }}
    
    - run: npm install --global yarn
    - run: yarn install
    
    - name: Run build with logging
      run: |
        yarn build | tee build.log
        echo "BUILD_STATUS=$?" >> $GITHUB_ENV
    
    - name: Create artifacts directory
      run: |
        mkdir -p artifacts
        cp -r coverage/ artifacts/
        cp -r dist/ artifacts/
        cp build.log artifacts/
        [ -d test-results ] && cp -r test-results/ artifacts/ || true
        [ -f junit.xml ] && cp junit.xml artifacts/ || true
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output-${{ matrix.db-type }}-node-${{ matrix.node-version }}
        path: artifacts/dist
        retention-days: 7
    
    - name: Upload build report
      uses: actions/upload-artifact@v4
      with:
        name: build-report-${{ matrix.db-type }}
        path: |
          artifacts/build.log
          artifacts/dist/stats.html  # If your build generates stats
        retention-days: 30
    
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.db-type }}
        path: |
          artifacts/coverage
          artifacts/junit.xml
          artifacts/test-results
        retention-days: 30
    
    - name: Upload coverage report
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ matrix.db-type }}
        path: artifacts/coverage/lcov-report
        retention-days: 30
    
